# **Import Pandas**

In [15]:
import pandas as pd

# **Load the CSV file**

In [16]:
df = pd.read_csv('/content/BCG.csv')

df

,Company,Fiscal Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Source/10-K
0,Microsoft,2023,"211,915","72,361","411,976","205,753","87,582",Microsoft 2023 10-K
1,Microsoft,2024,"245,122","88,136","512,163","243,686","118,548",Microsoft 2025 10-K
2,Microsoft,2025,"281,724","101,832","619,003","275,524","136,162",Microsoft 2025 10-K
3,Tesla,2023,"96,773","14,974","106,618","43,009","13,256",Tesla 2023 10-K
4,Tesla,2024,"97,690","7,153","122,070","48,390","14,923",Tesla 2025 10-K
5,Tesla,2025,"94,827","3,855","137,806","54,941","14,747",Tesla 2025 10-K
6,Apple,2023,"383,285","96,995","352,583","290,437","110,543",Apple 2023 10-K
7,Apple,2024,"391,035","93,736","364,980","308,030","118,254",Apple 2025 10-K
8,Apple,2025,"416,161","112,010","359,241","285,508","111,482",Apple 2025 10-K

# **Analyzing trends with pandas**

In [17]:
# Financial columns that should contain numbers
metrics = [
    'Total Revenue',
    'Net Income',
    'Total Assets',
    'Total Liabilities',
    'Operating Cash Flow'
]

# Remove commas and convert financial columns to numbers
for metric in metrics:
    df[metric] = (
        df[metric]
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.strip()
    )
    df[metric] = pd.to_numeric(df[metric], errors='coerce')

# Make sure Fiscal Year is numeric
df['Fiscal Year'] = pd.to_numeric(df['Fiscal Year'], errors='coerce')

# **Check the data**

In [18]:
print("Dataset shape:")
print(df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nFirst five rows:")
display(df.head())

Dataset shape:
(9, 8)

Missing values:
Company                0
Fiscal Year            0
Total Revenue          0
Net Income             0
Total Assets           0
Total Liabilities      0
Operating Cash Flow    0
Source/10-K            0
dtype: int64

First five rows:

,Company,Fiscal Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Source/10-K
0,Microsoft,2023,211915,72361,411976,205753,87582,Microsoft 2023 10-K
1,Microsoft,2024,245122,88136,512163,243686,118548,Microsoft 2025 10-K
2,Microsoft,2025,281724,101832,619003,275524,136162,Microsoft 2025 10-K
3,Tesla,2023,96773,14974,106618,43009,13256,Tesla 2023 10-K
4,Tesla,2024,97690,7153,122070,48390,14923,Tesla 2025 10-K

# **Sort the data**

In [19]:
df = df.sort_values(
    ['Company', 'Fiscal Year']
).reset_index(drop=True)

# **Calculate Year-over-Year Growth**

In [20]:
df['Revenue Growth (%)'] = (
    df.groupby('Company')['Total Revenue']
    .pct_change() * 100
)

df['Net Income Growth (%)'] = (
    df.groupby('Company')['Net Income']
    .pct_change() * 100
)

df['Assets Growth (%)'] = (
    df.groupby('Company')['Total Assets']
    .pct_change() * 100
)

df['Liabilities Growth (%)'] = (
    df.groupby('Company')['Total Liabilities']
    .pct_change() * 100
)

df['Operating Cash Flow Growth (%)'] = (
    df.groupby('Company')['Operating Cash Flow']
    .pct_change() * 100
)

# **Round percentage values**

In [21]:
# Find the highest and lowest growth for each financial metric

growth_columns = [
    'Revenue Growth (%)',
    'Net Income Growth (%)',
    'Assets Growth (%)',
    'Liabilities Growth (%)',
    'Operating Cash Flow Growth (%)'
]

for column in growth_columns:
    print("\n", column)
    print("Highest growth:")
    display(df.loc[df[column].idxmax(), ['Company', 'Fiscal Year', column]])

    print("Lowest growth:")
    display(df.loc[df[column].idxmin(), ['Company', 'Fiscal Year', column]])

 Revenue Growth (%)
Highest growth:

Company               Microsoft
Fiscal Year                2024
Revenue Growth (%)    15.669962
Name: 4, dtype: object

Lowest growth:

Company                  Tesla
Fiscal Year               2025
Revenue Growth (%)   -2.930699
Name: 8, dtype: object

 Net Income Growth (%)
Highest growth:

Company                  Microsoft
Fiscal Year                   2024
Net Income Growth (%)    21.800417
Name: 4, dtype: object

Lowest growth:

Company                      Tesla
Fiscal Year                   2024
Net Income Growth (%)   -52.230533
Name: 7, dtype: object

 Assets Growth (%)
Highest growth:

Company              Microsoft
Fiscal Year               2024
Assets Growth (%)     24.31865
Name: 4, dtype: object

Lowest growth:

Company                 Apple
Fiscal Year              2025
Assets Growth (%)   -1.572415
Name: 2, dtype: object

 Liabilities Growth (%)
Highest growth:

Company                   Microsoft
Fiscal Year                    2024
Liabilities Growth (%)    18.436183
Name: 4, dtype: object

Lowest growth:

Company                      Apple
Fiscal Year                   2025
Liabilities Growth (%)   -7.311625
Name: 2, dtype: object

 Operating Cash Flow Growth (%)
Highest growth:

Company                           Microsoft
Fiscal Year                            2024
Operating Cash Flow Growth (%)     35.35658
Name: 4, dtype: object

Lowest growth:

Company                              Apple
Fiscal Year                           2025
Operating Cash Flow Growth (%)   -5.726656
Name: 2, dtype: object

In [22]:
print("\nComplete Financial Dataset with Growth Rates:")
display(df)

Complete Financial Dataset with Growth Rates:

,Company,Fiscal Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow,Source/10-K,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Operating Cash Flow Growth (%)
0,Apple,2023,383285,96995,352583,290437,110543,Apple 2023 10-K,NaN,NaN,NaN,NaN,NaN
1,Apple,2024,391035,93736,364980,308030,118254,Apple 2025 10-K,2.021994,-3.359967,3.516052,6.057424,6.975566
2,Apple,2025,416161,112010,359241,285508,111482,Apple 2025 10-K,6.425512,19.495178,-1.572415,-7.311625,-5.726656
3,Microsoft,2023,211915,72361,411976,205753,87582,Microsoft 2023 10-K,NaN,NaN,NaN,NaN,NaN
4,Microsoft,2024,245122,88136,512163,243686,118548,Microsoft 2025 10-K,15.669962,21.800417,24.318650,18.436183,35.356580
5,Microsoft,2025,281724,101832,619003,275524,136162,Microsoft 2025 10-K,14.932156,15.539621,20.860546,13.065174,14.858117
6,Tesla,2023,96773,14974,106618,43009,13256,Tesla 2023 10-K,NaN,NaN,NaN,NaN,NaN
7,Tesla,2024,97690,7153,122070,48390,14923,Tesla 2025 10-K,0.947578,-52.230533,14.492862,12.511335,12.575438
8,Tesla,2025,94827,3855,137806,54941,14747,Tesla 2025 10-K,-2.930699,-46.106529,12.890964,13.537921,-1.179388

# **Company-Level Average Analysis**

In [26]:
company_summary = df.groupby('Company')[
    [
        'Total Revenue',
        'Net Income',
        'Total Assets',
        'Total Liabilities',
        'Operating Cash Flow'
    ]
].mean().round(2)

print("\nAverage Financial Performance by Company:")
display(company_summary)

Average Financial Performance by Company:

,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow
Company,,,,,
Apple,396827.00,100913.67,358934.67,294658.33,113426.33
Microsoft,246253.67,87443.00,514380.67,241654.33,114097.33
Tesla,96430.00,8660.67,122164.67,48780.00,14308.67

# **2023 to 2025 Percentage Change**

In [27]:
start = df[df['Fiscal Year'] == 2023].set_index('Company')
end = df[df['Fiscal Year'] == 2025].set_index('Company')

change = pd.DataFrame(index=start.index)

for metric in metrics:
    change[f'{metric} Change (%)'] = (
        (end[metric] / start[metric]) - 1
    ) * 100

change = change.round(2)

print("\nPercentage Change from 2023 to 2025:")
display(change)

Percentage Change from 2023 to 2025:

,Total Revenue Change (%),Net Income Change (%),Total Assets Change (%),Total Liabilities Change (%),Operating Cash Flow Change (%)
Company,,,,,
Apple,8.58,15.48,1.89,-1.70,0.85
Microsoft,32.94,40.73,50.25,33.91,55.47
Tesla,-2.01,-74.26,29.25,27.74,11.25

# **Financial Performance by Year**

In [28]:
year_summary = df.groupby('Fiscal Year')[
    [
        'Total Revenue',
        'Net Income',
        'Total Assets',
        'Total Liabilities',
        'Operating Cash Flow'
    ]
].sum().round(2)

print("\nCombined Financial Performance by Year:")
display(year_summary)

Combined Financial Performance by Year:

,Total Revenue,Net Income,Total Assets,Total Liabilities,Operating Cash Flow
Fiscal Year,,,,,
2023,691973,184330,871177,539199,211381
2024,733847,189025,999213,600106,251725
2025,792712,217697,1116050,615973,262391